import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { createClient } from '@/lib/supabase/server'

// Seed data — must stay in lock-step with supabase/seed.sql.
//
// Legacy grocery SKUs: stock_qty = 0 so they only show on the hidden
// /out-of-stock page (the store filters stock_qty > 0).
//
// GSK catalogue SKUs (from Chuan Seng Leong "GSK - Products Catalogue 2026"
// pages 1-5): original_price = RSP, sale_price = round(RSP * 0.9, 2),
// discount_pct = 10. Stock = 1000, expiry = 2027-12-31 (PDF has no expiry).
const SEED_PRODUCTS = [
  // ── LEGACY GROCERY (out of stock) ───────────────────────────
  { name: 'Coca-Cola Classic 24 x 320ml', description: 'Refreshing classic cola drink, 24 cans', category: 'beverages', original_price: 15.90, sale_price: 5.90, discount_pct: 63, expiry_date: '2025-09-30', stock_qty: 0, image_url: null },
  { name: 'Red Bull Energy Drink 4 x 250ml', description: 'Original energy drink with caffeine & taurine, 4 cans', category: 'beverages', original_price: 9.70, sale_price: 3.50, discount_pct: 64, expiry_date: '2025-08-15', stock_qty: 0, image_url: null },
  { name: 'Pokka Green Tea 24 x 300ml', description: 'Japanese-style green tea, no preservatives, 24 bottles', category: 'beverages', original_price: 14.40, sale_price: 5.50, discount_pct: 62, expiry_date: '2025-10-20', stock_qty: 0, image_url: null },
  { name: 'Milo 3-in-1 Instant Drink 15 sachets x 27g', description: 'Chocolate malt drink with milk, just add hot water', category: 'beverages', original_price: 7.95, sale_price: 2.90, discount_pct: 64, expiry_date: '2025-11-10', stock_qty: 0, image_url: null },
  { name: 'Tata Tea Premium Leaf Tea 250g', description: 'Strong Indian-style black tea, loose leaf', category: 'beverages', original_price: 5.30, sale_price: 2.10, discount_pct: 60, expiry_date: '2025-12-05', stock_qty: 0, image_url: null },
  { name: '100Plus Isotonic Drink 24 x 325ml', description: 'Isotonic sports drink with electrolytes, 24 cans', category: 'beverages', original_price: 14.90, sale_price: 5.50, discount_pct: 63, expiry_date: '2025-09-20', stock_qty: 0, image_url: null },
  { name: 'Indomie Mi Goreng Fried Noodles 5 x 80g', description: "Indonesia's most popular instant fried noodles, spicy", category: 'instant_noodles', original_price: 2.25, sale_price: 0.90, discount_pct: 60, expiry_date: '2025-07-15', stock_qty: 0, image_url: null },
  { name: 'Maggi 2-Minute Noodles Curry Flavour 5 x 79g', description: 'Classic curry-flavoured instant noodles', category: 'instant_noodles', original_price: 2.57, sale_price: 1.00, discount_pct: 61, expiry_date: '2025-08-10', stock_qty: 0, image_url: null },
  { name: 'Maggi 2-Minute Noodles Chicken Flavour 5 x 77g', description: 'Chicken-flavoured instant noodles, quick to cook', category: 'instant_noodles', original_price: 2.57, sale_price: 1.00, discount_pct: 61, expiry_date: '2025-07-30', stock_qty: 0, image_url: null },
  { name: 'Nissin Cup Noodles Seafood 6 x 75g', description: 'Japanese-style seafood cup noodles, just add hot water', category: 'instant_noodles', original_price: 6.90, sale_price: 2.80, discount_pct: 59, expiry_date: '2025-09-05', stock_qty: 0, image_url: null },
  { name: 'Ayam Brand Sardines in Tomato Sauce 215g', description: 'Tender sardines in rich tomato sauce, ready to eat', category: 'canned_goods', original_price: 2.15, sale_price: 0.85, discount_pct: 60, expiry_date: '2025-12-20', stock_qty: 0, image_url: null },
  { name: 'Ayam Brand Tuna Chunks in Water 185g', description: 'Skipjack tuna chunks in spring water, high protein', category: 'canned_goods', original_price: 2.40, sale_price: 0.95, discount_pct: 60, expiry_date: '2025-11-30', stock_qty: 0, image_url: null },
  { name: 'Ligo Sardines in Corn Oil 155g', description: 'Tender sardines in corn oil, popular Filipino-style brand', category: 'canned_goods', original_price: 1.60, sale_price: 0.65, discount_pct: 59, expiry_date: '2025-10-15', stock_qty: 0, image_url: null },
  { name: 'FairPrice Baked Beans in Tomato Sauce 420g', description: 'Hearty baked beans in tomato sauce, great with rice', category: 'canned_goods', original_price: 1.25, sale_price: 0.50, discount_pct: 60, expiry_date: '2026-01-10', stock_qty: 0, image_url: null },
  { name: 'Royal Umbrella Thai Jasmine Rice 5kg', description: 'Premium Thai hom mali fragrant rice, long grain', category: 'rice_grains', original_price: 11.25, sale_price: 4.50, discount_pct: 60, expiry_date: '2025-12-15', stock_qty: 0, image_url: null },
  { name: 'India Gate Basmati Rice (Classic) 2kg', description: 'Extra-long aged basmati rice from India, fragrant', category: 'rice_grains', original_price: 8.95, sale_price: 3.50, discount_pct: 61, expiry_date: '2025-11-20', stock_qty: 0, image_url: null },
  { name: 'Knife Brand Cooking Oil 2L', description: 'Refined palm olein cooking oil, suitable for deep frying', category: 'cooking_essentials', original_price: 5.40, sale_price: 2.10, discount_pct: 61, expiry_date: '2025-10-10', stock_qty: 0, image_url: null },
  { name: 'Maggi Oyster Sauce 510g', description: 'Rich umami oyster sauce, essential for Asian cooking', category: 'cooking_essentials', original_price: 3.15, sale_price: 1.25, discount_pct: 60, expiry_date: '2025-12-01', stock_qty: 0, image_url: null },
  { name: 'Knorr Chicken Stock Cubes 60g (6 cubes)', description: 'Flavour-packed chicken stock cubes for soups and stews', category: 'cooking_essentials', original_price: 2.10, sale_price: 0.85, discount_pct: 60, expiry_date: '2025-11-15', stock_qty: 0, image_url: null },
  { name: 'FairPrice Instant Curry Powder 250g', description: 'Fragrant curry powder blend, suitable for meat & vegetable curries', category: 'cooking_essentials', original_price: 2.95, sale_price: 1.15, discount_pct: 61, expiry_date: '2025-09-25', stock_qty: 0, image_url: null },
  { name: 'Lifebuoy Antibacterial Body Wash 900ml', description: 'Sea minerals & salt formula, 10x better germ protection', category: 'personal_care', original_price: 6.45, sale_price: 2.60, discount_pct: 60, expiry_date: '2025-08-20', stock_qty: 0, image_url: null },
  { name: 'Dove Deeply Nourishing Body Wash 1L', description: 'Gentle nourishing body wash with 1/4 moisturising cream', category: 'personal_care', original_price: 8.50, sale_price: 3.40, discount_pct: 60, expiry_date: '2025-07-25', stock_qty: 0, image_url: null },
  { name: 'Sunsilk Smooth & Manageable Shampoo 650ml', description: 'Anti-frizz shampoo with keratin & argan oil', category: 'personal_care', original_price: 6.90, sale_price: 2.75, discount_pct: 60, expiry_date: '2025-09-15', stock_qty: 0, image_url: null },
  { name: 'Head & Shoulders Anti-Dandruff Shampoo 650ml', description: 'Classic anti-dandruff formula with Pyrithione Zinc', category: 'personal_care', original_price: 11.90, sale_price: 4.80, discount_pct: 60, expiry_date: '2025-08-05', stock_qty: 0, image_url: null },
  { name: 'Glow & Lovely Advanced Multivitamin Face Cream 50g', description: 'Daily face cream with Vitamin B3 for radiant glow', category: 'personal_care', original_price: 4.50, sale_price: 1.80, discount_pct: 60, expiry_date: '2025-07-10', stock_qty: 0, image_url: null },
  { name: 'Vaseline Intensive Care Body Lotion 400ml', description: 'Deep moisturising lotion with micro-droplets of Vaseline jelly', category: 'personal_care', original_price: 7.90, sale_price: 3.15, discount_pct: 60, expiry_date: '2025-10-30', stock_qty: 0, image_url: null },
  { name: 'Colgate Anticavity Toothpaste 225g', description: 'Fluoride toothpaste for strong teeth & fresh breath', category: 'personal_care', original_price: 4.15, sale_price: 1.65, discount_pct: 60, expiry_date: '2026-01-20', stock_qty: 0, image_url: null },
  { name: "Lay's Classic Potato Chips 170g", description: 'Crispy classic salted potato chips, popular party snack', category: 'snacks', original_price: 5.35, sale_price: 2.10, discount_pct: 61, expiry_date: '2025-08-30', stock_qty: 0, image_url: null },
  { name: 'Britannia Good Day Butter Cookies 216g', description: 'Crunchy buttery cookies, popular Indian biscuit brand', category: 'snacks', original_price: 3.50, sale_price: 1.40, discount_pct: 60, expiry_date: '2025-10-05', stock_qty: 0, image_url: null },
  { name: 'Dutch Lady Full Cream UHT Milk 1L', description: 'Full cream UHT milk, long shelf life, rich & creamy', category: 'dairy', original_price: 2.70, sale_price: 1.05, discount_pct: 61, expiry_date: '2025-09-10', stock_qty: 0, image_url: null },

  // ── GSK CATALOGUE (pages 1-5, 10% off RSP, in stock) ────────
  // Panadol
  { name: 'Panadol Optizorb 500mg (20 caplets)', description: 'Paracetamol 500mg with Optizorb technology — fast relief for headache, body ache and fever. Pack of 20 caplets.', category: 'pain_relief', original_price: 7.95, sale_price: 7.16, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71010362.png' },
  { name: 'Panadol Extra Optizorb 500mg (20 caplets)', description: 'Paracetamol 500mg + caffeine 65mg. Extra-strength relief with Optizorb fast-absorption technology. Pack of 20 caplets.', category: 'pain_relief', original_price: 9.95, sale_price: 8.96, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71010430.png' },
  { name: 'Panadol Extra Optizorb 500mg (120 caplets)', description: 'Paracetamol 500mg + caffeine 65mg for extra-strength relief. Family value pack of 120 caplets.', category: 'pain_relief', original_price: 55.75, sale_price: 50.18, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71080447.png' },
  { name: 'Panadol Extra Optizorb 500mg (30 caplets)', description: 'Paracetamol 500mg + caffeine 65mg with Optizorb fast-absorption technology. Pack of 30 caplets.', category: 'pain_relief', original_price: 13.25, sale_price: 11.93, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71011284.png' },
  { name: 'Panadol Actifast 500mg (20 caplets)', description: 'Paracetamol 500mg with sodium bicarbonate for faster absorption — relief in minutes. Pack of 20 caplets.', category: 'pain_relief', original_price: 11.75, sale_price: 10.58, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71010515.png' },
  { name: 'Panadol Extend 665mg (18 caplets)', description: 'Extended-release paracetamol 665mg for up to 8 hours of relief from muscle and joint pain. Pack of 18 caplets.', category: 'pain_relief', original_price: 9.95, sale_price: 8.96, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71010608.png' },
  { name: 'Panadol Menstrual 500mg (20 caplets)', description: 'Paracetamol 500mg + pamabrom to relieve menstrual cramps, bloating and headache. Pack of 20 caplets.', category: 'pain_relief', original_price: 9.95, sale_price: 8.96, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71012013.png' },
  { name: 'Panadol Cold & Flu Hot Remedy 500mg (5 sachets)', description: 'Hot lemon drink with paracetamol, phenylephrine and vitamin C to relieve cold and flu symptoms. Pack of 5 sachets.', category: 'pain_relief', original_price: 8.75, sale_price: 7.88, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71010110.png' },
  { name: 'Panadol Cold & Flu Cold Relief 500mg (12 caplets)', description: 'Paracetamol, phenylephrine and caffeine to relieve blocked nose, headache and body ache from a cold. Pack of 12 caplets.', category: 'pain_relief', original_price: 11.95, sale_price: 10.76, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71010294.png' },
  { name: 'Panadol Cold & Flu Cough & Cold (16 caplets)', description: 'Paracetamol 500mg + phenylephrine + dextromethorphan — relieves cold symptoms plus dry cough. Pack of 16 caplets.', category: 'pain_relief', original_price: 14.45, sale_price: 13.01, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71001414.png' },
  { name: 'Panadol Cold & Flu Sinus Max 500mg (12 caplets)', description: 'Paracetamol 500mg + phenylephrine targets sinus pressure, headache and congestion. Pack of 12 caplets.', category: 'pain_relief', original_price: 11.95, sale_price: 10.76, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71010899.png' },
  { name: 'Panadol MiniCaps 500mg (12 caplets)', description: 'Smaller, smooth-coated paracetamol 500mg caplets — easier to swallow. Pack of 12 caplets.', category: 'pain_relief', original_price: 8.75, sale_price: 7.88, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71010561.png' },
  { name: 'Panadol Baby Suspension 1 month+ Strawberry (60ml)', description: 'Paracetamol 120mg/5ml oral suspension for babies from 1 month. Sugar-free strawberry flavour. 60ml bottle.', category: 'pain_relief', original_price: 9.75, sale_price: 8.78, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71019302.png' },
  { name: 'Panadol Kids Suspension 1-12 years (60ml)', description: 'Paracetamol 120mg/5ml oral suspension for children aged 1 to 12. Gentle on little tummies. 60ml bottle.', category: 'pain_relief', original_price: 10.75, sale_price: 9.68, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71010691.png' },
  { name: 'Panadol Kid Chewable 120mg Cherry (24 tablets)', description: 'Chewable paracetamol 120mg tablets for children — cherry flavour. Pack of 24 tablets.', category: 'pain_relief', original_price: 8.75, sale_price: 7.88, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71010315.png' },

  // Panaflex
  { name: 'Panadol Panaflex Hydro Heat Patch (2 patches)', description: 'Hydrogel heat patch delivers soothing warmth to relieve muscle and joint pain. 2 patches per pack.', category: 'pain_relief', original_price: 4.05, sale_price: 3.65, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71011025.png' },
  { name: 'Panadol Panaflex Heat Gel Patch (4 patches)', description: 'Cooling-to-warming gel patch for targeted relief of back, neck and shoulder pain. 4 patches per pack.', category: 'pain_relief', original_price: 7.30, sale_price: 6.57, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71011056.png' },
  { name: 'Panadol Panaflex Hot Patch (5 patches)', description: 'Self-heating patch that loosens stiff muscles and soothes aches. 5 patches per pack.', category: 'pain_relief', original_price: 6.60, sale_price: 5.94, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71014536.png' },

  // Voltaren
  { name: 'Voltaren Emulgel 2% (50g)', description: 'Diclofenac diethylammonium 2% topical gel — 12-hour relief for back, muscle and joint pain. 50g tube.', category: 'pain_relief', original_price: 25.15, sale_price: 22.64, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/71021784.png' },

  // Aquafresh
  { name: 'Aquafresh Kids Little Teeth Toothpaste 3-5 yrs (50ml)', description: "Fluoride toothpaste with a mild mint flavour, formulated for children's baby teeth. 50ml tube.", category: 'oral_care', original_price: 7.60, sale_price: 6.84, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72016713.png' },
  { name: 'Aquafresh Kids Big Teeth Toothpaste 6+ yrs (50ml)', description: 'Fluoride toothpaste for children transitioning to adult teeth. Gentle mint flavour. 50ml tube.', category: 'oral_care', original_price: 7.60, sale_price: 6.84, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72016720.png' },
  { name: 'Aquafresh Kids Little Teeth Toothpaste 3-5 yrs Value Pack (2 x 50ml)', description: 'Twin-pack of Aquafresh Little Teeth — fluoride toothpaste for kids aged 3-5. 2 x 50ml tubes.', category: 'oral_care', original_price: 12.35, sale_price: 11.12, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72018810.png' },
  { name: 'Aquafresh Kids Big Teeth Toothpaste 6+ yrs Value Pack (2 x 50ml)', description: 'Twin-pack of Aquafresh Big Teeth — fluoride toothpaste for kids 6 and above. 2 x 50ml tubes.', category: 'oral_care', original_price: 12.35, sale_price: 11.12, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72018827.png' },
  { name: 'Aquafresh Kids Milk Teeth Toothbrush 0-2 yrs', description: "Ultra-soft toothbrush with a small head and easy-grip handle, designed for baby's first teeth.", category: 'oral_care', original_price: 6.45, sale_price: 5.81, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72010929.png' },
  { name: 'Aquafresh Kids Little Teeth Toothbrush 3-5 yrs', description: 'Soft-bristle toothbrush with a chunky handle, sized for little hands and little teeth.', category: 'oral_care', original_price: 6.45, sale_price: 5.81, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72011759.png' },
  { name: 'Aquafresh Clean & Control Toothbrush Soft (3-pack)', description: 'Soft-bristle toothbrush with raised cleaning tips to reach between teeth. Pack of 3.', category: 'oral_care', original_price: 5.85, sale_price: 5.27, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72011480.png' },
  { name: 'Aquafresh Clean & Control Toothbrush Medium (3-pack)', description: 'Medium-bristle toothbrush with raised cleaning tips for everyday plaque removal. Pack of 3.', category: 'oral_care', original_price: 5.85, sale_price: 5.27, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72011473.png' },
  { name: 'Aquafresh Clean & Flex Toothbrush Soft (3-pack)', description: 'Flexible-neck toothbrush with soft bristles — gentle cleaning without gum irritation. Pack of 3.', category: 'oral_care', original_price: 5.85, sale_price: 5.27, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72010142.png' },
  { name: 'Aquafresh Clean & Flex Toothbrush Medium (3-pack)', description: 'Flexible-neck toothbrush with medium bristles for thorough daily cleaning. Pack of 3.', category: 'oral_care', original_price: 5.85, sale_price: 5.27, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72010159.png' },

  // Parodontax
  { name: 'Parodontax Daily Fluoride Toothpaste (90g)', description: 'Daily toothpaste with fluoride and stannous salts — helps stop and prevent bleeding gums. 90g tube.', category: 'oral_care', original_price: 9.65, sale_price: 8.69, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72028506.png' },
  { name: 'Parodontax Daily Whitening Toothpaste (90g)', description: 'Whitening toothpaste that also helps prevent bleeding gums. Gently removes surface stains. 90g tube.', category: 'oral_care', original_price: 9.20, sale_price: 8.28, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72023423.png' },
  { name: 'Parodontax Herbal Toothpaste (90g)', description: 'Herbal formulation with ginger, mint and eucalyptus — helps fight plaque and improve gum health. 90g tube.', category: 'oral_care', original_price: 9.65, sale_price: 8.69, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72023447.png' },

  // Polident
  { name: 'Polident 3-Minute Daily Denture Cleanser (36 tablets)', description: 'Effervescent cleansing tablets kill 99.9% of odour-causing bacteria on dentures in just 3 minutes. 36 tablets.', category: 'denture_care', original_price: 9.10, sale_price: 8.19, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72065160.png' },
  { name: 'Polident Whitening Daily Denture Cleanser (36 tablets)', description: 'Whitening effervescent tablets lift stains and freshen dentures daily. 36 tablets.', category: 'denture_care', original_price: 9.85, sale_price: 8.87, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72061107.png' },
  { name: 'Polident Pro Retainer Daily Cleanser (36 tablets)', description: 'Gentle effervescent tablets formulated for retainers, aligners and mouth guards. 36 tablets.', category: 'denture_care', original_price: 10.50, sale_price: 9.45, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72034758.png' },
  { name: 'Polident 3-Minute Daily Denture Cleanser Twin Pack (2 x 36 tablets)', description: 'Twin pack of Polident 3-Minute — effervescent tablets that clean dentures in minutes. 2 x 36 tablets.', category: 'denture_care', original_price: 13.85, sale_price: 12.47, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72038292.png' },
  { name: 'Polident Whitening Denture Cleanser Twin Pack (2 x 36 tablets)', description: 'Twin pack of Polident Whitening — lifts stains and freshens dentures daily. 2 x 36 tablets.', category: 'denture_care', original_price: 14.95, sale_price: 13.46, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72038285.png' },
  { name: 'Polident 3-Minute Daily Denture Cleanser Value Pack (16 + 2 tablets)', description: 'Starter value pack — 18 effervescent cleansing tablets for dentures. Cleans in 3 minutes.', category: 'denture_care', original_price: 5.00, sale_price: 4.50, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72035922.png' },
  { name: 'Polident Denture Adhesive Cream Fresh Mint (60g)', description: 'All-day hold denture adhesive with a fresh mint flavour. Seals out food particles. 60g tube.', category: 'denture_care', original_price: 14.00, sale_price: 12.60, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72035382.png' },
  { name: 'Polident Denture Adhesive Cream Flavour Free (60g)', description: 'All-day hold denture adhesive with no added flavour — for sensitive palates. 60g tube.', category: 'denture_care', original_price: 14.00, sale_price: 12.60, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72039381.png' },
  { name: 'Polident Max Hold & Seal Denture Adhesive (40g)', description: 'Extra-strong hold and seal formula — locks out food particles all day. 40g tube.', category: 'denture_care', original_price: 11.90, sale_price: 10.71, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72037841.png' },
  { name: 'Polident Max Hold & Seal Denture Adhesive (70g)', description: 'Extra-strong hold and seal formula in a larger value tube. Locks out food particles all day. 70g tube.', category: 'denture_care', original_price: 18.90, sale_price: 17.01, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72037827.png' },

  // ── GSK CATALOGUE (pages 6-16, 10% off RSP, in stock) ────────
  // Sensodyne
  { name: 'Sensodyne Complete Protection Cool Mint Toothpaste (100g)', description: 'Daily protection toothpaste for sensitive teeth — 10 benefits in one, with cool mint flavour. 100g tube.', category: 'oral_care', original_price: 10.20, sale_price: 9.18, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72049689.png' },
  { name: 'Sensodyne Complete Protection Fresh Breath Toothpaste (100g)', description: 'Daily sensitivity toothpaste with extra-fresh breath formula. 100g tube.', category: 'oral_care', original_price: 10.20, sale_price: 9.18, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72049719.png' },
  { name: 'Sensodyne Repair & Protect Toothpaste (100g)', description: 'Clinically proven to repair sensitive areas and build a protective layer. 100g tube.', category: 'oral_care', original_price: 10.20, sale_price: 9.18, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72046328.png' },
  { name: 'Sensodyne Repair & Protect Extra Fresh Toothpaste (100g)', description: 'Repairs sensitive teeth with an extra-fresh mint flavour. 100g tube.', category: 'oral_care', original_price: 10.20, sale_price: 9.18, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72047486.png' },
  { name: 'Sensodyne Repair & Protect Whitening Toothpaste (100g)', description: 'Repairs sensitive teeth while gently whitening daily. 100g tube.', category: 'oral_care', original_price: 10.20, sale_price: 9.18, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72047011.png' },
  { name: 'Sensodyne Rapid Relief Original Toothpaste (100g)', description: 'Rapid-acting sensitivity relief in 60 seconds — original mint flavour. 100g tube.', category: 'oral_care', original_price: 10.20, sale_price: 9.18, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72049503.png' },
  { name: 'Sensodyne Rapid Relief Whitening Toothpaste (100g)', description: 'Rapid 60-second sensitivity relief with daily whitening action. 100g tube.', category: 'oral_care', original_price: 10.20, sale_price: 9.18, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72049527.png' },
  { name: 'Sensodyne Sensitivity & Gum Toothpaste (100g)', description: 'Twin-action toothpaste for sensitive teeth and healthier gums. 100g tube.', category: 'oral_care', original_price: 10.20, sale_price: 9.18, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72042341.png' },
  { name: 'Sensodyne Sensitivity & Gum Whitening Toothpaste (100g)', description: 'Daily care for sensitive teeth and gums — with whitening. 100g tube.', category: 'oral_care', original_price: 10.20, sale_price: 9.18, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72042365.png' },
  { name: 'Sensodyne Sensitivity & Gum Extra Fresh Toothpaste (100g)', description: 'Sensitive teeth and gum protection with an extra-fresh flavour. 100g tube.', category: 'oral_care', original_price: 10.20, sale_price: 9.18, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72043357.png' },
  { name: 'Sensodyne Sensitivity & Gum Enamel Mint Toothpaste (100g)', description: 'Protects sensitive teeth, gums and enamel with a cooling mint flavour. 100g tube.', category: 'oral_care', original_price: 11.00, sale_price: 9.90, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72047636.png' },
  { name: 'Sensodyne Clinical White Stain Protector Toothpaste (100g)', description: 'Clinically proven to whiten and protect sensitive teeth from stains. 100g tube.', category: 'oral_care', original_price: 13.00, sale_price: 11.70, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72041908.png' },
  { name: 'Sensodyne Clinical White Enamel Strengthening Toothpaste (100g)', description: 'Clinical whitening formula that also strengthens enamel. 100g tube.', category: 'oral_care', original_price: 13.00, sale_price: 11.70, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72042196.png' },
  { name: 'Sensodyne Clinical White Stain Protector Travel Toothpaste (20g)', description: 'Travel-size Sensodyne Clinical White stain-protection toothpaste. 20g tube.', category: 'oral_care', original_price: 2.95, sale_price: 2.66, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72041878.png' },
  { name: 'Sensodyne Fresh Mint Toothpaste Twin Pack (2 x 100g)', description: 'Twin-pack of Sensodyne Fresh Mint daily sensitivity toothpaste. 2 x 100g tubes.', category: 'oral_care', original_price: 6.05, sale_price: 5.45, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72046134.png' },
  { name: 'Sensodyne Gum Care Toothpaste Twin Pack (2 x 100g)', description: 'Twin-pack of Sensodyne Gum Care — sensitivity and gum health. 2 x 100g tubes.', category: 'oral_care', original_price: 6.05, sale_price: 5.45, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72046141.png' },
  { name: 'Sensodyne Gentle Whitening Toothpaste Twin Pack (2 x 100g)', description: 'Twin-pack of Sensodyne Gentle Whitening — sensitivity with daily whitening. 2 x 100g tubes.', category: 'oral_care', original_price: 6.05, sale_price: 5.45, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72044672.png' },
  { name: 'Sensodyne Multi Care Toothpaste Twin Pack (2 x 100g)', description: 'Twin-pack of Sensodyne Multi Care — all-round sensitivity protection. 2 x 100g tubes.', category: 'oral_care', original_price: 6.05, sale_price: 5.45, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72043508.png' },
  { name: 'Sensodyne Fresh Mint Toothpaste (75g)', description: 'Daily fresh-mint toothpaste for sensitive teeth. 75g tube.', category: 'oral_care', original_price: 4.00, sale_price: 3.60, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72042976.png' },
  { name: 'Sensodyne Multicare Toothbrush Soft (3-pack)', description: 'Soft-bristle toothbrush designed for sensitive teeth and gums. Pack of 3.', category: 'oral_care', original_price: 4.20, sale_price: 3.78, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72042860.png' },
  { name: 'Sensodyne Complete Protection Toothbrush Soft (Buy 2 Free 1)', description: 'Soft-bristle sensitivity toothbrush — buy 2 get 1 free promotional pack.', category: 'oral_care', original_price: 14.00, sale_price: 12.60, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72041191.png' },
  { name: 'Sensodyne Sensitivity & Gum Toothbrush Soft (Buy 2 Free 1)', description: 'Soft-bristle toothbrush for sensitive teeth and gums — buy 2 get 1 free promotional pack.', category: 'oral_care', original_price: 14.00, sale_price: 12.60, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/72043249.png' },

  // Scott's (supplements)
  { name: "Scott's Cod Liver Oil Capsules (500 capsules)", description: 'Classic cod liver oil capsules — omega-3, vitamin A and D for daily immunity. 500 capsules per bottle.', category: 'supplements', original_price: 36.10, sale_price: 32.49, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74016028.png' },
  { name: "Scott's Vitamin C Mix Berries Pastilles (100g)", description: 'Chewable vitamin C pastilles in mixed-berries flavour — daily immunity support. 100g bottle.', category: 'supplements', original_price: 11.95, sale_price: 10.76, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74011049.png' },
  { name: "Scott's Vitamin C Orange Pastilles (100g)", description: 'Chewable vitamin C pastilles in orange flavour — daily immunity support. 100g bottle.', category: 'supplements', original_price: 11.95, sale_price: 10.76, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74011629.png' },
  { name: "Scott's Vitamin C Black Currant Pastilles (100g)", description: 'Chewable vitamin C pastilles in black currant flavour — daily immunity support. 100g bottle.', category: 'supplements', original_price: 11.95, sale_price: 10.76, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74016103.png' },
  { name: "Scott's Vitamin C Mix Berries Zipper Pack (30g)", description: 'Resealable snack pack of mixed-berries vitamin C pastilles. 30g pouch.', category: 'supplements', original_price: 4.15, sale_price: 3.74, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74011360.png' },
  { name: "Scott's Vitamin C Orange Zipper Pack (30g)", description: 'Resealable snack pack of orange vitamin C pastilles. 30g pouch.', category: 'supplements', original_price: 4.15, sale_price: 3.74, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74011643.png' },
  { name: "Scott's Vitamin C Black Currant Zipper Pack (30g)", description: 'Resealable snack pack of black currant vitamin C pastilles. 30g pouch.', category: 'supplements', original_price: 4.15, sale_price: 3.74, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74016097.png' },
  { name: "Scott's DHA Gummies Black Currant (60 gummies)", description: 'Soft chewable DHA gummies for kids — brain-boosting omega-3 with a black-currant twist. 60 gummies per bottle.', category: 'supplements', original_price: 24.50, sale_price: 22.05, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74013005.png' },
  { name: "Scott's DHA Gummies Orange (60 gummies)", description: 'Soft chewable DHA gummies for kids — brain-boosting omega-3 in orange flavour. 60 gummies per bottle.', category: 'supplements', original_price: 24.50, sale_price: 22.05, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74012305.png' },
  { name: "Scott's DHA Gummies Strawberry (60 gummies)", description: 'Soft chewable DHA gummies for kids — brain-boosting omega-3 in strawberry flavour. 60 gummies per bottle.', category: 'supplements', original_price: 24.50, sale_price: 22.05, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74012381.png' },
  { name: "Scott's DHA Gummies Black Currant Zipper Pack (15 gummies)", description: "Resealable snack pack of kids' DHA gummies in black-currant flavour. 15 gummies.", category: 'supplements', original_price: 6.50, sale_price: 5.85, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74012978.png' },
  { name: "Scott's DHA Gummies Orange Zipper Pack (15 gummies)", description: "Resealable snack pack of kids' DHA gummies in orange flavour. 15 gummies.", category: 'supplements', original_price: 6.50, sale_price: 5.85, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74012329.png' },
  { name: "Scott's DHA Gummies Strawberry Zipper Pack (15 gummies)", description: "Resealable snack pack of kids' DHA gummies in strawberry flavour. 15 gummies.", category: 'supplements', original_price: 6.50, sale_price: 5.85, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74012404.png' },

  // Eno (digestive)
  { name: 'Eno Fruit Salt Plain (100g)', description: 'Fast-acting antacid fruit salt — relieves heartburn, indigestion and acidity. 100g bottle.', category: 'digestive', original_price: 6.50, sale_price: 5.85, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74020017.png' },
  { name: 'Eno Fruit Salt Orange (100g)', description: 'Fast-acting antacid fruit salt with a refreshing orange flavour. 100g bottle.', category: 'digestive', original_price: 6.50, sale_price: 5.85, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74020055.png' },
  { name: 'Eno Fruit Salt Lemon (100g)', description: 'Fast-acting antacid fruit salt with a zesty lemon flavour. 100g bottle.', category: 'digestive', original_price: 6.50, sale_price: 5.85, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74020031.png' },
  { name: 'Eno Fruit Salt Lemon Sachets (48 x 4.3g)', description: 'Portable single-dose sachets of lemon-flavoured antacid fruit salt. Box of 48.', category: 'digestive', original_price: 49.20, sale_price: 44.28, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/74000086.png' },

  // Drapolene (skincare)
  { name: 'Drapolene Cream (55g)', description: 'Gentle antiseptic cream that prevents and treats nappy rash. Suitable for babies. 55g tube.', category: 'skincare', original_price: 12.20, sale_price: 10.98, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/75024230.png' },

  // Otrivin (cold_flu)
  { name: 'Otrivin Nasal Congestion Drops 0.05% (10ml)', description: 'Decongestant nasal drops for babies and children — fast relief from blocked nose. 10ml bottle.', category: 'cold_flu', original_price: 12.75, sale_price: 11.48, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/76025847.png' },

  // Centrum (vitamins)
  { name: 'Centrum Advance Multivitamin (60 tablets)', description: 'Complete daily multivitamin for adults with 24 nutrients for energy, immunity and metabolism. 60 tablets.', category: 'vitamins', original_price: 38.95, sale_price: 35.06, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78010231.png' },
  { name: 'Centrum Silver Multivitamin 50+ (60 tablets)', description: 'Multivitamin tailored for adults 50+ — heart, brain and eye support. 60 tablets.', category: 'vitamins', original_price: 44.50, sale_price: 40.05, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78010255.png' },
  { name: 'Centrum Advance Multivitamin (100 tablets)', description: 'Complete daily multivitamin for adults — 24 nutrients for energy and immunity. Value pack of 100 tablets.', category: 'vitamins', original_price: 59.50, sale_price: 53.55, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78010013.png' },
  { name: 'Centrum Silver Multivitamin 50+ (100 tablets)', description: 'Multivitamin for adults 50+ — heart, brain and eye support. Value pack of 100 tablets.', category: 'vitamins', original_price: 67.95, sale_price: 61.16, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78010456.png' },
  { name: 'Centrum for Men Multivitamin (60 tablets)', description: "Men's multivitamin with nutrients for energy, muscle function and heart health. 60 tablets.", category: 'vitamins', original_price: 45.50, sale_price: 40.95, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78010517.png' },
  { name: 'Centrum for Women Multivitamin (60 tablets)', description: "Women's multivitamin with iron, calcium, B vitamins and more. 60 tablets.", category: 'vitamins', original_price: 45.50, sale_price: 40.95, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78010531.png' },
  { name: 'Centrum for Men 50+ Multivitamin (60 tablets)', description: 'Multivitamin for men 50+ with nutrients supporting heart, muscle and prostate health. 60 tablets.', category: 'vitamins', original_price: 49.95, sale_price: 44.96, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78011385.png' },
  { name: 'Centrum for Women 50+ Multivitamin (60 tablets)', description: 'Multivitamin for women 50+ with nutrients for heart, bone and metabolism support. 60 tablets.', category: 'vitamins', original_price: 49.95, sale_price: 44.96, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78011415.png' },
  { name: 'Centrum for Men Multivitamin (100 tablets)', description: "Men's daily multivitamin — value pack of 100 tablets.", category: 'vitamins', original_price: 68.50, sale_price: 61.65, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78012443.png' },
  { name: 'Centrum for Women Multivitamin (100 tablets)', description: "Women's daily multivitamin — value pack of 100 tablets.", category: 'vitamins', original_price: 68.50, sale_price: 61.65, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78012436.png' },
  { name: 'Centrum for Men 50+ Multivitamin (100 tablets)', description: 'Multivitamin for men 50+ — value pack of 100 tablets.', category: 'vitamins', original_price: 76.50, sale_price: 68.85, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78012948.png' },
  { name: 'Centrum for Women 50+ Multivitamin (100 tablets)', description: 'Multivitamin for women 50+ — value pack of 100 tablets.', category: 'vitamins', original_price: 76.50, sale_price: 68.85, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78012931.png' },

  // Caltrate (supplements)
  { name: 'Caltrate 600+D3 Triple Action Bone & Muscle Health (60 tablets)', description: 'Calcium 600mg + vitamin D3 500IU + magnesium + zinc — triple action for bones and muscles. 60 tablets.', category: 'supplements', original_price: 37.95, sale_price: 34.16, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78020821.png' },
  { name: 'Caltrate 600+D3 Dual Action Bone & Muscle Health (60 tablets)', description: 'Calcium 600mg + vitamin D3 500IU — dual action for stronger bones and muscles. 60 tablets.', category: 'supplements', original_price: 33.95, sale_price: 30.56, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78020814.png' },
  { name: 'Caltrate 600+D3 Triple Action Bone & Muscle Health (100 tablets)', description: 'Calcium + vitamin D3 + magnesium + zinc — triple action. Value pack of 100 tablets.', category: 'supplements', original_price: 57.95, sale_price: 52.16, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78021392.png' },
  { name: 'Caltrate 600+D3 Dual Action Bone & Muscle Health (100 tablets)', description: 'Calcium 600mg + vitamin D3 500IU for bone and muscle health. Value pack of 100 tablets.', category: 'supplements', original_price: 51.50, sale_price: 46.35, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78021385.png' },
  { name: 'Caltrate 600+D 1000IU Bone & Muscle Health (60 tablets)', description: 'Calcium 600mg + high-strength vitamin D 1000IU for bones and muscles. 60 tablets.', category: 'supplements', original_price: 43.50, sale_price: 39.15, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78021637.png' },
  { name: 'Caltrate 1000IU Vitamin D Bone & Muscle Health (60 softgels)', description: 'High-strength vitamin D 1000IU softgels — supports calcium absorption and muscle function. 60 softgels.', category: 'supplements', original_price: 21.50, sale_price: 19.35, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78023600.png' },
  { name: 'Caltrate Joint Health UC-II Collagen (30 tablets)', description: 'UC-II undenatured type II collagen for joint comfort and flexibility. 30 tablets.', category: 'supplements', original_price: 50.50, sale_price: 45.45, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78023479.png' },
  { name: 'Caltrate Joint Health UC-II Collagen (90 tablets)', description: 'UC-II collagen for joint comfort — 3-month supply. 90 tablets.', category: 'supplements', original_price: 136.50, sale_price: 122.85, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78023334.png' },
  { name: 'Caltrate Joint Speed Hops UC-II Collagen (42 tablets)', description: 'Fast-acting joint support with UC-II collagen plus hops extract. 42 tablets.', category: 'supplements', original_price: 67.95, sale_price: 61.16, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78023654.png' },

  // Robitussin (cold_flu)
  { name: 'Robitussin EX Expectorant Syrup (100ml)', description: 'Expectorant cough syrup that helps loosen and clear chesty coughs. 100ml bottle.', category: 'cold_flu', original_price: 12.95, sale_price: 11.66, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78031117.png' },

  // Imedeen (supplements)
  { name: 'Imedeen Time Perfection (60 tablets)', description: 'Beauty-from-within supplement with BioMarine Complex — supports skin firmness and radiance. 60 tablets.', category: 'supplements', original_price: 206.95, sale_price: 186.26, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78055818.png' },
  { name: 'Imedeen Prime Renewal (120 tablets)', description: 'Advanced skin supplement for women 50+ — supports density, firmness and smoothness. 120 tablets.', category: 'supplements', original_price: 259.95, sale_price: 233.96, discount_pct: 10, expiry_date: '2027-12-31', stock_qty: 1000, image_url: '/products/78051253.png' },
]

export async function POST() {
  // Auth check: only admins can seed products
  const serverSupabase = await createClient()
  const { data: { user } } = await serverSupabase.auth.getUser()
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }
  const { data: profile } = await serverSupabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single()
  if (profile?.role !== 'admin') {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  const supabase = createAdminClient()

  // Check if already seeded
  const { count } = await supabase.from('products').select('*', { count: 'exact', head: true })
  if ((count ?? 0) > 0) {
    return NextResponse.json({ error: 'Products already seeded. Delete existing products first.' }, { status: 409 })
  }

  const { error, data } = await supabase
    .from('products')
    .insert(SEED_PRODUCTS.map((p) => ({ ...p, is_active: true })))
    .select('id')

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  return NextResponse.json({ seeded: data?.length ?? 0 })
}
