-- Elitez ESOP — D1 schema.
-- Append-only event log with hash chain. State is derived by replaying events.
-- Apply with:  wrangler d1 migrations apply elitez-esop-db --remote

CREATE TABLE IF NOT EXISTS events (
  id           TEXT PRIMARY KEY,        -- ev_xxx — generated by Worker
  type         TEXT NOT NULL,           -- e.g. grant_approved, exercise_submitted
  at           TEXT NOT NULL,           -- ISO timestamp UTC
  payload      TEXT NOT NULL,           -- JSON
  prev_hash    TEXT,                    -- hash of previous event (NULL for first)
  hash         TEXT NOT NULL,           -- SHA-256 of (type|at|payload|prev_hash) hex
  actor_email  TEXT,                    -- from Cloudflare Access JWT
  actor_role   TEXT,                    -- 'committee' | 'holder' | 'admin'
  created_at   INTEGER NOT NULL,        -- unix ms
  client_ip    TEXT,                    -- for audit
  notes        TEXT
);

CREATE INDEX IF NOT EXISTS idx_events_at ON events(at);
CREATE INDEX IF NOT EXISTS idx_events_actor ON events(actor_email);
CREATE INDEX IF NOT EXISTS idx_events_type ON events(type);

-- Optional KV for small counters / cached snapshots
CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT,
  updated_at INTEGER
);
