-- Auto-generated by scripts/build-seed-migration.mjs
-- Idempotent via `on conflict do nothing`. Re-running is safe.
-- Generated 51 seed events from assets/data.json.
begin;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_27777a0960e9da87', 'grant_approved', '{"holder_id":"1","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":60000}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  null,
  encode(digest('' || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"1","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":60000}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_81f60ce9ef83633f', 'grant_approved', '{"holder_id":"1","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":71595}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_27777a0960e9da87'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_27777a0960e9da87'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"1","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":71595}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_b4fec81a3c4efdad', 'grant_approved', '{"holder_id":"2","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":60000}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_81f60ce9ef83633f'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_81f60ce9ef83633f'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"2","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":60000}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_dbed241988febc6c', 'grant_approved', '{"holder_id":"2","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":71595}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_b4fec81a3c4efdad'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_b4fec81a3c4efdad'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"2","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":71595}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_86eb0dd3054bc899', 'grant_approved', '{"holder_id":"3","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":35000}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_dbed241988febc6c'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_dbed241988febc6c'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"3","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":35000}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_53bd104f9a08901e', 'grant_approved', '{"holder_id":"3","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":66926}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_86eb0dd3054bc899'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_86eb0dd3054bc899'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"3","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":66926}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_ec3c9fb69babc603', 'grant_approved', '{"holder_id":"4","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":40000}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_53bd104f9a08901e'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_53bd104f9a08901e'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"4","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":40000}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_fffffb4d44be1fee', 'grant_approved', '{"holder_id":"4","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":69261}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_ec3c9fb69babc603'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_ec3c9fb69babc603'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"4","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":69261}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_be171a40346e965a', 'grant_approved', '{"holder_id":"5","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":40000}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_fffffb4d44be1fee'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_fffffb4d44be1fee'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"5","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":40000}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_1bb3bc2ed8618bde', 'grant_approved', '{"holder_id":"5","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":66926}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_be171a40346e965a'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_be171a40346e965a'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"5","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":66926}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_8aa720e383d21962', 'grant_approved', '{"holder_id":"6","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":26000}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_1bb3bc2ed8618bde'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_1bb3bc2ed8618bde'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"6","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":26000}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_48dfddbfed8fcc29', 'grant_approved', '{"holder_id":"6","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":52140}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_8aa720e383d21962'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_8aa720e383d21962'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"6","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":52140}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_af3a1ee909dc8e2d', 'grant_approved', '{"holder_id":"7","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":25000}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_48dfddbfed8fcc29'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_48dfddbfed8fcc29'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"7","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":25000}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_2641020fc485a4c5', 'grant_approved', '{"holder_id":"7","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":40467}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_af3a1ee909dc8e2d'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_af3a1ee909dc8e2d'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"7","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":40467}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_cccae64a4780930e', 'grant_approved', '{"holder_id":"8","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":20000}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_2641020fc485a4c5'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_2641020fc485a4c5'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"8","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":20000}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_b73d4b755dea0695', 'grant_approved', '{"holder_id":"8","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":45914}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_cccae64a4780930e'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_cccae64a4780930e'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"8","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":45914}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_edb392f0e97f27f3', 'grant_approved', '{"holder_id":"9","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":20000}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_b73d4b755dea0695'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_b73d4b755dea0695'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"9","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":20000}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_006bcfe396d33701', 'grant_approved', '{"holder_id":"9","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":48249}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_edb392f0e97f27f3'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_edb392f0e97f27f3'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"9","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":48249}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_e362fada993d9d0a', 'grant_approved', '{"holder_id":"10","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":20000}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_006bcfe396d33701'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_006bcfe396d33701'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"10","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":20000}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_b6abab11c6654c9b', 'grant_approved', '{"holder_id":"10","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":40467}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_e362fada993d9d0a'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_e362fada993d9d0a'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"10","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":40467}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_c81c50191e0d9642', 'grant_approved', '{"holder_id":"11","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":20000}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_b6abab11c6654c9b'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_b6abab11c6654c9b'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"11","fy":"FY2022","grant_date":"2022-07-15","letter_date":"2022-07-15","qty":20000}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_2c34b6bbd3b2ab58', 'grant_approved', '{"holder_id":"11","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":55253}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_c81c50191e0d9642'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_c81c50191e0d9642'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"11","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":55253}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_77f75534dc98a6dc', 'grant_approved', '{"holder_id":"12","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":45914}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_2c34b6bbd3b2ab58'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_2c34b6bbd3b2ab58'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"12","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":45914}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_213e211d0bdaa83b', 'grant_approved', '{"holder_id":"13","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":45914}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_77f75534dc98a6dc'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_77f75534dc98a6dc'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"13","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":45914}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_1513c6bccc1495c5', 'grant_approved', '{"holder_id":"14","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":36576}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_213e211d0bdaa83b'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_213e211d0bdaa83b'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"14","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":36576}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_5aa2918f12fd664a', 'grant_approved', '{"holder_id":"15","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":41245}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_1513c6bccc1495c5'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_1513c6bccc1495c5'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"15","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":41245}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_7b4463c2fc632aa2', 'grant_approved', '{"holder_id":"16","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":40467}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_5aa2918f12fd664a'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_5aa2918f12fd664a'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"16","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":40467}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_920817bb6d2ed1fe', 'grant_approved', '{"holder_id":"17","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":29572}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_7b4463c2fc632aa2'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_7b4463c2fc632aa2'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"17","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":29572}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_a59663be70ed4da8', 'grant_approved', '{"holder_id":"18","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":41245}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_920817bb6d2ed1fe'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_920817bb6d2ed1fe'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"18","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":41245}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_6954cf6ce6c3dda8', 'grant_approved', '{"holder_id":"19","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":45914}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_a59663be70ed4da8'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_a59663be70ed4da8'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"19","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":45914}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_cf9eb8e9a65eb3e1', 'grant_approved', '{"holder_id":"20","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":63035}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_6954cf6ce6c3dda8'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_6954cf6ce6c3dda8'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"20","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":63035}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_3053c286196f9611', 'grant_approved', '{"holder_id":"21","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":36576}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_cf9eb8e9a65eb3e1'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_cf9eb8e9a65eb3e1'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"21","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":36576}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_7e38dc8a8a8c3753', 'grant_approved', '{"holder_id":"22","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":56809}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_3053c286196f9611'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_3053c286196f9611'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"22","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":56809}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_cf9f9f4eaa76b1c4', 'grant_approved', '{"holder_id":"23","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":43580}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_7e38dc8a8a8c3753'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_7e38dc8a8a8c3753'),'') || 'grant_approved' || '2026-04-23T00:00:00Z' || '{"holder_id":"23","fy":"FY2024","grant_date":"2024-07-31","letter_date":"2024-07-31","qty":43580}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_447914c0cf97a4a5', 'valuation_added', '{"fy":"FY2021","ebitda":2866596,"multiple":6,"fmv":0.5303}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_cf9f9f4eaa76b1c4'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_cf9f9f4eaa76b1c4'),'') || 'valuation_added' || '2026-04-23T00:00:00Z' || '{"fy":"FY2021","ebitda":2866596,"multiple":6,"fmv":0.5303}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_f8e01e6c37e4fbef', 'valuation_added', '{"fy":"FY2022","ebitda":-690139,"multiple":6,"fmv":0.1969,"note":"Negative EBITDA — NTA floor applied"}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_447914c0cf97a4a5'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_447914c0cf97a4a5'),'') || 'valuation_added' || '2026-04-23T00:00:00Z' || '{"fy":"FY2022","ebitda":-690139,"multiple":6,"fmv":0.1969,"note":"Negative EBITDA — NTA floor applied"}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_8d76c0b75737fe4c', 'valuation_added', '{"fy":"FY2023","ebitda":2221089,"multiple":6,"fmv":0.4109}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_f8e01e6c37e4fbef'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_f8e01e6c37e4fbef'),'') || 'valuation_added' || '2026-04-23T00:00:00Z' || '{"fy":"FY2023","ebitda":2221089,"multiple":6,"fmv":0.4109}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_1c184e3473112f3e', 'valuation_added', '{"fy":"FY2024","ebitda":6146972,"multiple":6,"fmv":1.1372}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_8d76c0b75737fe4c'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_8d76c0b75737fe4c'),'') || 'valuation_added' || '2026-04-23T00:00:00Z' || '{"fy":"FY2024","ebitda":6146972,"multiple":6,"fmv":1.1372}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_bfb0e9ee4bfdbe5a', 'valuation_added', '{"fy":"FY2025","ebitda":4624269,"multiple":6,"fmv":0.8555,"active":true,"firm_value":27745614,"exercise_price":0.0856}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_1c184e3473112f3e'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_1c184e3473112f3e'),'') || 'valuation_added' || '2026-04-23T00:00:00Z' || '{"fy":"FY2025","ebitda":4624269,"multiple":6,"fmv":0.8555,"active":true,"firm_value":27745614,"exercise_price":0.0856}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_92206f25a15f3d70', 'valuation_activated', '{"fy":"FY2025"}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_bfb0e9ee4bfdbe5a'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_bfb0e9ee4bfdbe5a'),'') || 'valuation_activated' || '2026-04-23T00:00:00Z' || '{"fy":"FY2025"}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_7a8ea9bb84dae573', 'data_quality_flagged', '{"sev":"high","topic":"Kan Siew Weng IC","issue":"Stored as scientific notation in xlsx; needs clean re-entry."}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_92206f25a15f3d70'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_92206f25a15f3d70'),'') || 'data_quality_flagged' || '2026-04-23T00:00:00Z' || '{"sev":"high","topic":"Kan Siew Weng IC","issue":"Stored as scientific notation in xlsx; needs clean re-entry."}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_c2736ec4ef8b338c', 'data_quality_flagged', '{"sev":"high","topic":"FMCG ownership %","issue":"KPMG: 100%; xlsx Trading Rules implies 80/20 with Eevann. Resolve before go-live."}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_7a8ea9bb84dae573'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_7a8ea9bb84dae573'),'') || 'data_quality_flagged' || '2026-04-23T00:00:00Z' || '{"sev":"high","topic":"FMCG ownership %","issue":"KPMG: 100%; xlsx Trading Rules implies 80/20 with Eevann. Resolve before go-live."}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_ae2399d5cf6768e7', 'data_quality_flagged', '{"sev":"high","topic":"Committee composition","issue":"Legal: 3 Major Shareholders + 2 senior employees; Guidebook: 2 employees + 1 Management. Legal wins — update Guidebook."}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_c2736ec4ef8b338c'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_c2736ec4ef8b338c'),'') || 'data_quality_flagged' || '2026-04-23T00:00:00Z' || '{"sev":"high","topic":"Committee composition","issue":"Legal: 3 Major Shareholders + 2 senior employees; Guidebook: 2 employees + 1 Management. Legal wins — update Guidebook."}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_386643d9da2c7e3c', 'data_quality_flagged', '{"sev":"medium","topic":"Yeoh Ser How nationality","issue":"Singaporean in 2024 sheet; Malaysian in 2025 sheet. Confirm with HR."}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_ae2399d5cf6768e7'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_ae2399d5cf6768e7'),'') || 'data_quality_flagged' || '2026-04-23T00:00:00Z' || '{"sev":"medium","topic":"Yeoh Ser How nationality","issue":"Singaporean in 2024 sheet; Malaysian in 2025 sheet. Confirm with HR."}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_87e4f966bb87933e', 'data_quality_flagged', '{"sev":"medium","topic":"Factor 1 threshold","issue":"Guidebook: >5 yrs = 2 pts; xlsx used 4 yrs = 2 pts. Guidebook governs."}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_386643d9da2c7e3c'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_386643d9da2c7e3c'),'') || 'data_quality_flagged' || '2026-04-23T00:00:00Z' || '{"sev":"medium","topic":"Factor 1 threshold","issue":"Guidebook: >5 yrs = 2 pts; xlsx used 4 yrs = 2 pts. Guidebook governs."}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_ca3dea0fb151899f', 'data_quality_flagged', '{"sev":"medium","topic":"Toh Hui Leong (Daryl)","issue":"Dual entries in xlsx (active #5 + terminated #29). Treated as Left pending confirmation."}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_87e4f966bb87933e'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_87e4f966bb87933e'),'') || 'data_quality_flagged' || '2026-04-23T00:00:00Z' || '{"sev":"medium","topic":"Toh Hui Leong (Daryl)","issue":"Dual entries in xlsx (active #5 + terminated #29). Treated as Left pending confirmation."}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_e382930b441bd0f1', 'data_quality_flagged', '{"sev":"medium","topic":"Pre-Commencement grants","issue":"FY2022 and FY2024 grants pre-date Plan commencement (5 Oct 2025). Confirm instrument of regularisation."}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_ca3dea0fb151899f'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_ca3dea0fb151899f'),'') || 'data_quality_flagged' || '2026-04-23T00:00:00Z' || '{"sev":"medium","topic":"Pre-Commencement grants","issue":"FY2022 and FY2024 grants pre-date Plan commencement (5 Oct 2025). Confirm instrument of regularisation."}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_5b27725552b824ee', 'data_quality_flagged', '{"sev":"low","topic":"FY2023 zero grants","issue":"Confirm intentional gap vs missing records."}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_e382930b441bd0f1'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_e382930b441bd0f1'),'') || 'data_quality_flagged' || '2026-04-23T00:00:00Z' || '{"sev":"low","topic":"FY2023 zero grants","issue":"Confirm intentional gap vs missing records."}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_a12615f5a35ae576', 'data_quality_flagged', '{"sev":"low","topic":"Leaver determinations","issue":"Samion, Philip, Asmond — Good vs Bad Leaver determination pending."}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_5b27725552b824ee'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_5b27725552b824ee'),'') || 'data_quality_flagged' || '2026-04-23T00:00:00Z' || '{"sev":"low","topic":"Leaver determinations","issue":"Samion, Philip, Asmond — Good vs Bad Leaver determination pending."}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_fbcfe4d72ae231a1', 'data_quality_flagged', '{"sev":"low","topic":"Valuation multiple choice","issue":"Internal 6× vs KPMG 8–9×. Conservative internal reduces taxable perquisite at exercise but also reduces exit optics. Conscious policy?"}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_a12615f5a35ae576'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_a12615f5a35ae576'),'') || 'data_quality_flagged' || '2026-04-23T00:00:00Z' || '{"sev":"low","topic":"Valuation multiple choice","issue":"Internal 6× vs KPMG 8–9×. Conservative internal reduces taxable perquisite at exercise but also reduces exit optics. Conscious policy?"}', 'sha256'), 'hex'))
on conflict (id) do nothing;
insert into public.events(id, type, payload, at, actor_role, prev_hash, hash)
values('ev_seed_1de99a0491c9858f', 'dividend_declared', '{"name":"Adept Academy Pte Ltd Sale","declared":"2025-12-31","trigger":"Sale of subsidiary","gross":1400000,"broker_fee":56000,"staff_set_aside":30000,"distributable":1314000,"non_esop_allocations":[{"recipient":"Tommy","pct":0.2,"amount":262800},{"recipient":"EGPL","pct":0.8,"amount":1051200}],"esop_pool":70054.46,"esop_shares_entitled":2056942,"per_share":0.0341,"condition":"Must exercise ESOP within one month of declaration"}'::jsonb, '2026-04-23T00:00:00Z', 'system',
  (select hash from public.events where id = 'ev_seed_fbcfe4d72ae231a1'),
  encode(digest(coalesce((select hash from public.events where id = 'ev_seed_fbcfe4d72ae231a1'),'') || 'dividend_declared' || '2026-04-23T00:00:00Z' || '{"name":"Adept Academy Pte Ltd Sale","declared":"2025-12-31","trigger":"Sale of subsidiary","gross":1400000,"broker_fee":56000,"staff_set_aside":30000,"distributable":1314000,"non_esop_allocations":[{"recipient":"Tommy","pct":0.2,"amount":262800},{"recipient":"EGPL","pct":0.8,"amount":1051200}],"esop_pool":70054.46,"esop_shares_entitled":2056942,"per_share":0.0341,"condition":"Must exercise ESOP within one month of declaration"}', 'sha256'), 'hex'))
on conflict (id) do nothing;
commit;
